frase = 'quero ganhar dinheiro'
print(frase[8])
print(frase[4:10])
print(frase[4:10:2])
print(frase[:10])
print(frase[4::3])
print(frase[::3])
print(len(frase))
print(frase.count('a'))
print(frase.count('o',0,15))
print(frase.find('banana'))
print('quero' in frase)
print(frase.replace('quero', 'Alagoa'))
print(frase.upper())
print(frase.capitalize())
print(frase.title())
print(frase.split())
print('-'.join(frase))